services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://neelamdheerajkumar:DrNltjHB5DTevVUE@attendance.itpn8hv.mongodb.net/?retryWrites=true&w=majority&appName=Attendance

    expose:
      - "2000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
